CircleCI Commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,7 @@ version: 2.1
 executors:
   azure-executor:
     docker:
-      - image: ubuntu:20.04
+      - image: ubuntu:20.04  # Use an Ubuntu image with apt-get
     working_directory: ~/project
 
 orbs:
@@ -17,17 +17,12 @@ jobs:
       - checkout
       - run:
           name: Build with Maven
-          command: mvn clean package
-      - persist_to_workspace:
-          root: ~/project
-          paths:
-            - target
+          command: mvn clean install
 
   deploy:
     executor: azure-executor
     steps:
-      - attach_workspace:
-          at: ~/project
+      - checkout
       - run:
           name: Install curl and gnupg
           command: |
@@ -46,8 +41,13 @@ jobs:
       - run:
           name: Deploy to Azure App Service
           command: |
-            az webapp deploy --resource-group eshwar --name eshwar-backend --src-path target/ems-backend-0.0.1-SNAPSHOT.jar --type zip
-            echo "Deployment successful"
+            if [ -f "/home/circleci/project/target/ems-backend-0.0.1-SNAPSHOT.jar" ]; then
+              az webapp deploy --resource-group eshwar --name eshwar-backend --src-path /home/circleci/project/target/ems-backend-0.0.1-SNAPSHOT.jar --type zip
+              echo "Deployment successful"
+            else
+              echo "File not found or no permissions"
+              exit 1
+            fi
 
 workflows:
   build-and-deploy:
