Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -47,8 +47,13 @@ jobs:
       - run:
           name: Deploy to Azure App Service
           command: |
-            az webapp deploy --resource-group eshwar --name eshwar-backend --src-path ems-backend-0.0.1-SNAPSHOT.jar --type zip
-            echo "Deployment successful"
+            if [ -f target/ems-backend-0.0.1-SNAPSHOT.jar ]; then
+              az webapp deploy --resource-group eshwar --name eshwar-backend --src-path target/ems-backend-0.0.1-SNAPSHOT.jar --type zip
+              echo "Deployment successful"
+            else
+              echo "File not found in target directory"
+              exit 1
+            fi
 
 workflows:
   build-and-deploy:
