Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,15 +33,25 @@ jobs:
             curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            
       - run:
+          name: Export AZURE_TENANT_ID
+          command: |
+            export AZURE_TENANT_ID="118b2919-e434-405b-9f3c-3a829eba55f9" # Set your tenant ID here
+            echo "AZURE_TENANT_ID set to $AZURE_TENANT_ID"
+            
+      - run:
           name: Debug Environment Variables
           command: |
             echo "AZURE_CLIENT_ID: $AZURE_CLIENT_ID"
             echo "AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET"
             echo "AZURE_TENANT_ID: $AZURE_TENANT_ID"
+            if [[ -z "$AZURE_TENANT_ID" ]]; then
+              echo "Error: AZURE_TENANT_ID is not set"
+              exit 1
+            fi
       - run:
           name: Log in to Azure
           command: |
-            az login --service-principal -u $AZURE_CLIENT_ID -p "$AZURE_CLIENT_SECRET" --tenant $TENANT_ID --debug
+            az login --service-principal -u $AZURE_CLIENT_ID -p "$AZURE_CLIENT_SECRET" --tenant $AZURE_TENANT_ID --debug
       - run:
           name: Deploy to Azure App Service
           command: |
